// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kyeiasieptsrmzsqqzne.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt5ZWlhc2llcHRzcm16c3Fxem5lIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY1ODMwNzMsImV4cCI6MjA3MjE1OTA3M30.PYXL9Gd4m6JIgQxaxSpHUReJLvBF2ElCId5czvHOMu4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});